# Generated by Django 2.1.7 on 2019-03-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_eventpagegalleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='intro',
            field=models.CharField(default='', max_length=250),
        ),
    ]
